---

version: '3.1'

services:

  graph:
    build:
      context: .
    image: informaticsmatters/neo4j:4.4.9
    container_name: neo4j

  graph-enterprise:
    build:
      context: .
      dockerfile: Dockerfile-enterprise
    image: informaticsmatters/neo4j:4.4.9-enterprise
    container_name: neo4j-enterprise

  graph-loader:
    build:
      context: .
      dockerfile: Dockerfile-s3-loader
    image: informaticsmatters/neo4j-s3-loader:4.4.9
    container_name: neo4j-s3-loader
